import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parents[1] / "config.env")

APP_RUN_MODE = os.environ.get("APP_RUN_MODE", "DEV")
HEROKU_WEB_URL = os.environ["HEROKU_WEB_URL"]
SCHULPORTAL_AJAX_URL = os.environ["SCHULPORTAL_AJAX_URL"]
SCHULPORTAL_LOGIN_URL = os.environ["SCHULPORTAL_LOGIN_URL"]
SCHULPORTAL_NACHRICHTEN_URL = os.environ["SCHULPORTAL_NACHRICHTEN_URL"]
SCHULPORTAL_MEINUNTERRICHT_URL = os.environ["SCHULPORTAL_MEINUNTERRICHT_URL"]
SCHULPORTAL_START_URL = os.environ["SCHULPORTAL_START_URL"]
SCHULPORTAL_VERTRETUNGSPLAN_URL = os.environ["SCHULPORTAL_VERTRETUNGSPLAN_URL"]
TELEGRAM_API_TOKEN = os.environ["TELEGRAM_API_TOKEN"]
